spring:
  application:
    name: consumers
  cloud:
    str
server:
  port: 9003
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.17.14:8999/eureka/
feign:
  hystrix:
    enabled: false