server:
  port: 8999

spring:
  redis:
    database: 0
    host: 192.168.17.14
    port: 6379
    cluster:
      nodes: 192.168.17.14:9001,192.168.17.14:9002,192.168.17.14:9003,192.168.17.15:9001,192.168.17.15:9002,192.168.17.15:9003
    lettuce:
      pool:
        min-idle: 0
        max-wait: -1ms
        max-idle: 8
        max-active: 8
  data:
    mongodb:
      database: test
      host: 192.168.17.14
      port: 27017

  datasource:
    data-username: root
    data-password: 217024
    url: jdbc:mysql://192.168.17.14:3306/study?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath*:com/ruanbanhai/springboot/demo/dao/**.xml
  type-aliases-package: com.ruanbanhai.springboot.demo.pojo


redis:
    database: 1
    host: 192.168.17.15
    port: 6379
    pool:
      max-active: 8
      max-idle: 1
      max-wait: 0
      min-idle: 0
    timeout: 0

eureka:
  instance:
    hostname: eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.17.14:8999/eureka/



